if(new URLSearchParams(location.search).get('embedded')==='1')document.documentElement.classList.add('assistant-embedded');
import {demoMenu,calculateEstimate,interpretDemo,demoNotice} from './demo-menu.mjs';
import {assistantConfig} from './assistant-config.mjs';
const $=id=>document.getElementById(id),money=c=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(c/100);
let menu=demoMenu,items=[],connected=false,requestKey=crypto.randomUUID(),busy=false;
function message(text,customer=false){const p=document.createElement('p');p.className='chat-message'+(customer?' customer':'');p.textContent=text;$('messages').append(p);$('messages').scrollTop=$('messages').scrollHeight;}
async function backend(action,body={}){if(!assistantConfig.endpoint)throw new Error('The hosted service is not connected yet.');const response=await fetch(assistantConfig.endpoint,{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+assistantConfig.publicKey,apikey:assistantConfig.publicKey},body:JSON.stringify({action,...body})});if(!response.headers.get('Content-Type')?.includes('application/json'))throw new Error('The service is unavailable. Try again later.');const data=await response.json();if(!response.ok)throw new Error(data.error||'Unable to complete this request.');return data;}
function showMenu(){ $('menu-item').replaceChildren();$('menu-prices').replaceChildren();for(const item of menu){const option=document.createElement('option');option.value=item.id;option.textContent=item.name+' — '+money(item.price_cents)+' / '+item.unit;$('menu-item').append(option);const p=document.createElement('p');p.textContent=option.textContent;$('menu-prices').append(p);}}
function estimate(){const result=calculateEstimate(items,menu);$('estimate-summary').textContent='Sample estimate: '+money(result.subtotal_cents)+' · view details';$('estimate').replaceChildren();if(!result.lines.length){const p=document.createElement('p');p.textContent='No items yet. Choose from the sample menu.';$('estimate').append(p);}for(const line of result.lines){const row=document.createElement('div');row.className='estimate-line';const p=document.createElement('p');p.textContent=line.quantity+' × '+line.name+' ('+line.unit+')';const cost=document.createElement('p');cost.textContent=money(line.price_cents)+' each · '+money(line.total_cents);const remove=document.createElement('button');remove.type='button';remove.textContent='Remove';remove.setAttribute('aria-label','Remove '+line.name);remove.addEventListener('click',()=>{items=items.filter(i=>i.id!==line.id);requestKey=crypto.randomUUID();estimate();});row.append(p,cost,remove);$('estimate').append(row);}const total=document.createElement('p');total.className='estimate-total';total.textContent='Food subtotal: '+money(result.subtotal_cents);const note=document.createElement('p');note.textContent=demoNotice;$('estimate').append(total,note);$('save-demo').disabled=!connected||!items.length||busy;return result;}
$('item-form').addEventListener('submit',event=>{event.preventDefault();try{const updated=[...items,{id:$('menu-item').value,quantity:Number($('item-quantity').value)}];items=calculateEstimate(updated,menu).lines.map(l=>({id:l.id,quantity:l.quantity}));requestKey=crypto.randomUUID();estimate();}catch(error){message(error.message);}});
$('clear-estimate').addEventListener('click',()=>{items=[];requestKey=crypto.randomUUID();estimate();$('demo-order-status').textContent=connected?'Ready to save a practice request.':'Database connection pending. Nothing is saved.';});
$('chat-message').addEventListener('keydown',event=>{if(event.key==='Enter'&&!event.shiftKey&&!event.isComposing&&event.keyCode!==229){event.preventDefault();if(!busy)$('chat-form').requestSubmit();}});
$('chat-form').addEventListener('submit',async event=>{event.preventDefault();if(busy)return;const text=$('chat-message').value.trim();if(!text)return;busy=true;$('chat-send').disabled=true;message(text,true);$('chat-message').value='';$('chat-progress').textContent='Bubba’s is typing…';try{const response=connected?await backend('chat',{message:text,items}):interpretDemo(text,menu);message(response.reply);if(response.mode)$('assistant-mode').textContent=response.mode==='ai'?'Bubba’s Assistant · demo menu':'Guided demo · conversation temporarily unavailable';if(Array.isArray(response.items)){items=calculateEstimate(response.items,menu).lines.map(l=>({id:l.id,quantity:l.quantity}));requestKey=crypto.randomUUID();estimate();}}catch(error){message(error.message+' Your estimate is unchanged.');if(!$('chat-message').value)$('chat-message').value=text;}finally{busy=false;$('chat-send').disabled=false;$('chat-progress').textContent='';$('chat-message').focus();estimate();}});
$('demo-order-form').addEventListener('submit',async event=>{event.preventDefault();if(busy||!connected||!items.length)return;busy=true;estimate();try{const result=await backend('order',{items,name:$('demo-name').value,date:$('demo-date').value,notes:$('demo-notes').value,request_key:requestKey});$('demo-order-status').textContent='Practice request saved: '+result.id+'. This is not a real booking. Saved food subtotal: '+money(result.estimate.subtotal_cents);requestKey=crypto.randomUUID();}catch(error){$('demo-order-status').textContent=error.message+' Nothing has been confirmed. Your details remain here.';}finally{busy=false;estimate();}});
for(const id of ['demo-name','demo-date','demo-notes'])$(id).addEventListener('input',()=>{requestKey=crypto.randomUUID();});
showMenu();estimate();
if(assistantConfig.endpoint){backend('catalog').then(result=>{calculateEstimate([],result.menu);menu=result.menu;connected=true;showMenu();estimate();$('assistant-mode').textContent=result.mode==='ai'?'Bubba’s Assistant · demo menu':'Guided demo · hosted database connected';$('demo-order-status').textContent='Use fictional details. Practice requests will be saved to the demo database.';}).catch(error=>{$('assistant-mode').textContent='Guided offline demo · '+error.message;});}
