import {demoMenu,calculateEstimate,demoNotice} from './demo-menu.mjs';import {assistantConfig as c} from './assistant-config.mjs';
const $=id=>document.getElementById(id),money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(n/100);
let menu=demoMenu,items=[],connected=false,busy=false,key=crypto.randomUUID(),saved=false;
async function api(action,body={}){const r=await fetch(c.endpoint,{method:'POST',headers:{'Content-Type':'application/json',apikey:c.publicKey,Authorization:'Bearer '+c.publicKey},body:JSON.stringify({action,...body})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Unable to save request.');return d;}
function changed(){key=crypto.randomUUID();saved=false;$('request-result').textContent='';renderCart();}
function renderMenu(){$('order-menu').replaceChildren();for(const m of menu){const form=document.createElement('form');form.className='estimate-line';const title=document.createElement('h3');title.textContent=m.name;const price=document.createElement('p');price.textContent=money(m.price_cents)+' / '+m.unit;const label=document.createElement('label');label.textContent='Quantity';const input=document.createElement('input');input.type='number';input.min=1;input.max=500;input.step=1;input.value=1;input.required=true;input.setAttribute('aria-label',m.name+' quantity');const add=document.createElement('button');add.textContent='Add to cart';form.append(title,price,label,input,add);form.addEventListener('submit',e=>{e.preventDefault();try{items=calculateEstimate([...items,{id:m.id,quantity:Number(input.value)}],menu).lines.map(l=>({id:l.id,quantity:l.quantity}));changed();}catch(error){$('order-status').textContent=error.message;}});$('order-menu').append(form);}}
function renderCart(){const estimate=calculateEstimate(items,menu);$('cart').replaceChildren();if(!items.length)$('cart').textContent='Your cart is empty. Add items from the menu.';for(const l of estimate.lines){const row=document.createElement('div');row.className='estimate-line';const text=document.createElement('p');text.textContent=l.name+' · '+money(l.price_cents)+' each';const qty=document.createElement('input');qty.type='number';qty.min=1;qty.max=500;qty.step=1;qty.value=l.quantity;qty.setAttribute('aria-label',l.name+' cart quantity');qty.addEventListener('change',()=>{try{const updated=items.map(i=>i.id===l.id?{...i,quantity:Number(qty.value)}:i);calculateEstimate(updated,menu);items=updated;changed();}catch(error){qty.value=l.quantity;$('order-status').textContent=error.message;}});const total=document.createElement('p');total.textContent=money(l.total_cents);const remove=document.createElement('button');remove.type='button';remove.textContent='Remove';remove.setAttribute('aria-label','Remove '+l.name);remove.addEventListener('click',()=>{items=items.filter(i=>i.id!==l.id);changed();});row.append(text,qty,total,remove);$('cart').append(row);}const total=document.createElement('p');total.className='estimate-total';total.textContent='Estimated food subtotal: '+money(estimate.subtotal_cents);const notice=document.createElement('p');notice.textContent=demoNotice;$('cart').append(total,notice);$('submit-request').disabled=!connected||!items.length||busy||saved;}
$('event-request').addEventListener('input',()=>{key=crypto.randomUUID();saved=false;renderCart();});
$('event-request').addEventListener('submit',async e=>{e.preventDefault();if(busy||saved||!connected||!items.length)return;busy=true;renderCart();try{const result=await api('order',{items,name:$('request-name').value,date:$('request-date').value,notes:$('request-notes').value,request_key:key,event:{email:$('request-email').value,phone:$('request-phone').value,location:$('request-location').value,guest_count:Number($('request-guests').value),event_type:$('request-type').value}});saved=true;$('request-result').textContent='Practice event request saved: '+result.id+'. Food subtotal: '+money(result.estimate.subtotal_cents)+'. Staff can view it in the request desk. No booking or email has been confirmed.';}catch(error){$('request-result').textContent=error.message+' Your cart and details are still here.';}finally{busy=false;renderCart();}});
renderMenu();renderCart();api('catalog').then(d=>{menu=d.menu;connected=true;renderMenu();renderCart();$('order-status').textContent='Ready to build and save a practice event request.';}).catch(()=>{$('order-status').textContent='The request service is unavailable. You can explore sample prices, but submission is disabled.';});
