import {PublicError,providerConfig,verifyPayment,refundPayment,checkRefund} from './payment-providers.mjs';
// Static assets are generated by build.mjs, outside customer-data storage.
import {assets} from './assets.mjs';
const now=()=>new Date().toISOString();
const json=(body,status=200)=>new Response(JSON.stringify(body),{status,headers:{'Content-Type':'application/json','Cache-Control':'private, no-store','X-Content-Type-Options':'nosniff'}});
export function staffIdentity(request,env){
 const id=request.headers.get('oai-authenticated-user-id');
 const email=request.headers.get('oai-authenticated-user-email')?.toLowerCase();
 const allowed=(env.STAFF_EMAILS||'condonbradley21@gmail.com').split(',').map(s=>s.trim().toLowerCase()).filter(Boolean);
 return id&&email&&allowed.includes(email)?email:null;
}
function database(env){if(!env.DB) throw new PublicError('Order storage is temporarily unavailable. Please try again or call Bubba’s.',503);return env.DB;}
function sameOrigin(request){if(request.headers.get('Origin')!==new URL(request.url).origin) throw new PublicError('Please submit from the Bubba’s website.',403);}
async function input(request){if(Number(request.headers.get('Content-Length'))>12000)throw new PublicError('Request too large.',413);const value=await request.text();if(value.length>12000)throw new PublicError('Request too large.',413);try{return JSON.parse(value);}catch{throw new PublicError('Invalid request.');}}
export function validateOrder(body){
 const lengths={name:100,email:150,phone:40,location:250,preferred_date:10,guest_count:6,event_type:100,message:1500};
 const output={};for(const [key,max] of Object.entries(lengths)){if(typeof body[key]!=='string')throw new PublicError('Please complete the event details.');output[key]=body[key].trim();if(output[key].length>max)throw new PublicError('One of the fields is too long.');}
 for(const key of ['name','email','phone','location','message'])if(!output[key])throw new PublicError('Please complete all required fields.');
 if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(output.email))throw new PublicError('Enter a valid email address.');
 if(output.preferred_date){const date=new Date(output.preferred_date);if(!/^\d{4}-\d{2}-\d{2}$/.test(output.preferred_date)||Number.isNaN(date.valueOf())||date.toISOString().slice(0,10)!==output.preferred_date)throw new PublicError('Enter a valid event date.');}
 if(output.guest_count&&(!/^\d+$/.test(output.guest_count)||Number(output.guest_count)<1||Number(output.guest_count)>100000))throw new PublicError('Enter a valid guest count.');
 if(body.website)throw new PublicError('Unable to submit this request.');
 if(!/^[a-f0-9-]{36}$/.test(body.request_key||''))throw new PublicError('Please reload the form and try again.');
 return output;
}
async function digest(text){return Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(text))),x=>x.toString(16).padStart(2,'0')).join('');}
async function recordOrder(request,env){
 sameOrigin(request);const body=await input(request);const order=validateOrder(body);const db=database(env);const hash=await digest(JSON.stringify(order));
 const existing=await db.prepare('SELECT id,payload_hash FROM orders WHERE request_key = ?').bind(body.request_key).first();
 if(existing){if(existing.payload_hash!==hash)throw new PublicError('This request was already saved. Reload to submit a different event.',409);return json({id:existing.id},200);}
 const id='BBQ-'+crypto.randomUUID().toUpperCase();const time=now();
 await db.batch([
 db.prepare('INSERT INTO orders (id,request_key,payload_hash,name,email,phone,location,preferred_date,guest_count,event_type,message,status,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(request_key) DO NOTHING').bind(id,body.request_key,hash,order.name,order.email,order.phone,order.location,order.preferred_date,order.guest_count,order.event_type,order.message,'requested',time,time),
 db.prepare('INSERT INTO activity (order_id,actor,action,created_at) SELECT ?,?,?,? WHERE EXISTS (SELECT 1 FROM orders WHERE id=?)').bind(id,'Customer','Order request saved; email delivery must be completed through the form.',time,id)
 ]);
 const saved=await db.prepare('SELECT id,payload_hash FROM orders WHERE request_key = ?').bind(body.request_key).first();
 if(saved.payload_hash!==hash)throw new PublicError('Request key was already used for another event.',409);
 return json({id:saved.id},201);
}
async function orderDetail(db,id){const order=await db.prepare('SELECT * FROM orders WHERE id=?').bind(id).first();if(!order)throw new PublicError('Order not found.',404);delete order.request_key;delete order.payload_hash;const payments=await db.prepare('SELECT * FROM payments WHERE order_id=? ORDER BY created_at').bind(id).all();const activity=await db.prepare('SELECT actor,action,created_at FROM activity WHERE order_id=? ORDER BY id DESC').bind(id).all();return {order,payments:payments.results,activity:activity.results};}
function audit(db,id,actor,action){return db.prepare('INSERT INTO activity (order_id,actor,action,created_at) VALUES (?,?,?,?)').bind(id,actor,action,now());}
async function staffApi(request,env,path,actor){
 const db=database(env);
 if(path==='/api/staff/orders'&&request.method==='GET'){
  const u=new URL(request.url);const page=Math.max(0,Math.min(10000,Number(u.searchParams.get('page'))||0));
  const rows=await db.prepare('SELECT id,name,email,preferred_date,event_type,status,created_at FROM orders ORDER BY created_at DESC LIMIT 51 OFFSET ?').bind(page*50).all();
  return json({orders:rows.results.slice(0,50),hasMore:rows.results.length>50,page,providers:providerConfig(env),staff:actor});
 }
 const match=path.match(/^\/api\/staff\/orders\/(BBQ-[A-F0-9-]{36})(?:\/(status|payments|refund|refund-status))?$/);if(!match)throw new PublicError('Not found.',404);
 const [,id,action]=match;if(request.method==='GET'&&!action)return json(await orderDetail(db,id));
 if(request.method!=='POST'||!action)throw new PublicError('Method not allowed.',405);
 sameOrigin(request);const body=await input(request);const details=await orderDetail(db,id);
 if(action==='status'){
  if(!['requested','confirmed','completed','cancelled'].includes(body.status))throw new PublicError('Choose a valid order status.');
  if(details.order.status==='cancelled'&&body.status!=='cancelled')throw new PublicError('Cancelled orders cannot be reopened. Create a new request.',409);
  const reason=String(body.reason||'').trim();if(reason.length>500)throw new PublicError('Keep the reason under 500 characters.');if(body.status==='cancelled'&&!reason)throw new PublicError('Add a cancellation reason.');
  const result=await db.batch([db.prepare('UPDATE orders SET status=?, cancellation_reason=?,updated_at=? WHERE id=? AND status=?').bind(body.status,body.status==='cancelled'?reason:null,now(),id,details.order.status),db.prepare('INSERT INTO activity (order_id,actor,action,created_at) SELECT ?,?,?,? WHERE changes()=1').bind(id,actor,'Status: '+body.status+(reason?' — '+reason:''),now())]);
  if(result[0].meta.changes!==1)throw new PublicError('This order changed in another session. Refresh before updating it.',409);return json(await orderDetail(db,id));
 }
 if(action==='payments'){
  const provider=String(body.provider||'');const providerId=String(body.provider_id||'').trim();const verified=await verifyPayment(env,provider,providerId,id);
  const already=await db.prepare('SELECT order_id FROM payments WHERE provider=? AND provider_id=?').bind(provider,providerId).first();if(already)throw new PublicError('This transaction is already linked to an order.',409);
  await db.batch([db.prepare('INSERT INTO payments (id,order_id,provider,provider_id,amount,currency,mode,refund_status,created_at) VALUES (?,?,?,?,?,?,?,?,?)').bind(crypto.randomUUID(),id,provider,providerId,verified.amount,verified.currency,verified.mode,'none',now()),audit(db,id,actor,'Verified '+provider+' payment linked: '+providerId)]);return json(await orderDetail(db,id));
 }
 const payment=details.payments.find(p=>p.id===body.payment_id);if(!payment)throw new PublicError('Payment not found.',404);
 if(action==='refund-status'){
  if(!payment.refund_id)throw new PublicError('No provider refund reference yet. Check the transaction in the provider account before further action.',409);
  const result=await checkRefund(env,payment);await db.batch([db.prepare('UPDATE payments SET refund_status=? WHERE id=?').bind(result.status,payment.id),audit(db,id,actor,'Refund checked: '+result.status)]);return json(await orderDetail(db,id));
 }
 if(details.order.status!=='cancelled')throw new PublicError('Cancel the order before refunding.',409);
 if(body.confirm_order_id!==id)throw new PublicError('Confirm the order ID before refunding.');
 if(payment.refund_status!=='none')throw new PublicError('A refund has already been requested. Check its status or review the provider account; do not submit another refund.',409);
 // Persist a one-time claim before contacting the provider. Unknown results never unlock a second refund.
 const verified=await verifyPayment(env,payment.provider,payment.provider_id,id);if(verified.amount!==payment.amount||verified.mode!==payment.mode)throw new PublicError('Payment details changed. Review the provider account.',409);
 const key=crypto.randomUUID();const claim=await db.prepare("UPDATE payments SET refund_key=?,refund_status='processing',refund_started_at=? WHERE id=? AND refund_status='none'").bind(key,now(),payment.id).run();
 if(claim.meta.changes!==1)throw new PublicError('Another refund request is already in progress.',409);
 try{
  const result=await refundPayment(env,{...payment,refund_key:key});
  await db.batch([db.prepare('UPDATE payments SET refund_id=?,refund_status=? WHERE id=?').bind(result.id,result.status,payment.id),audit(db,id,actor,'Refund '+result.status+': '+result.id)]);
 }catch(error){await db.batch([db.prepare("UPDATE payments SET refund_status='review_required' WHERE id=?").bind(payment.id),audit(db,id,actor,'Refund requires provider review. Do not submit another refund.')]);throw new PublicError('Refund result needs review. Check this transaction in your payment provider account; no second refund will be submitted from this portal.',502);}
 return json(await orderDetail(db,id));
}
function serve(path,request){const asset=assets[path];if(!asset)return new Response('Not found',{status:404});const body=asset.binary?Uint8Array.from(atob(asset.data),c=>c.charCodeAt(0)):asset.data;return new Response(request.method==='HEAD'?null:body,{headers:{'Content-Type':asset.type,'X-Content-Type-Options':'nosniff','Cache-Control':path==='/staff.html'?'private, no-store':'public, max-age=60','Referrer-Policy':'strict-origin-when-cross-origin'}});}
export default {async fetch(request,env){
 try{
  const path=new URL(request.url).pathname;
  if(path==='/api/orders'&&request.method==='POST')return await recordOrder(request,env);
  if(path.startsWith('/api/staff/')){const actor=staffIdentity(request,env);if(!actor)return json({error:'Sign in with an authorized staff account.'},403);return await staffApi(request,env,path,actor);}
  if(path==='/staff.html'||path==='/staff'){
   if(!request.headers.get('oai-authenticated-user-id'))return Response.redirect(new URL('/signin-with-chatgpt?return_to=%2Fstaff.html',request.url),302);
   if(!staffIdentity(request,env))return new Response('This account does not have staff access. Contact the business owner.',{status:403,headers:{'Cache-Control':'no-store'}});
   return serve('/staff.html',request);
  }
  if(request.method!=='GET'&&request.method!=='HEAD')return json({error:'Method not allowed.'},405);
  return serve(path==='/'?'/index.html':path,request);
 }catch(error){if(!(error instanceof PublicError))console.error('Order portal request failed',error.name);return json({error:error instanceof PublicError?error.message:'Unable to complete this request. Your details have not been cleared. Please try again.'},error.status||503);}
}};
